# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mq}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Darby"]
  s.date = %q{2009-12-16}
  s.description = %q{A Rails gem that generates an MVC stack that does email queuing}
  s.email = %q{matt@matt-darby.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "README.textile"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "README.textile",
     "Rakefile",
     "VERSION",
     "generators/mq/USAGE",
     "generators/mq/mq_generator.rb",
     "generators/mq/templates/create_email_table.rb",
     "generators/mq/templates/email.rb",
     "generators/mq/templates/emails_controller.rb",
     "generators/mq/templates/spec/email_spec.rb",
     "generators/mq/templates/spec/emails_controller_spec.rb",
     "generators/mq/templates/spec/emails_routing_spec.rb",
     "generators/mq/templates/views/_email.html.erb",
     "generators/mq/templates/views/index.html.erb",
     "lib/mq.rb",
     "mq.gemspec",
     "test/helper.rb",
     "test/test_mq.rb"
  ]
  s.homepage = %q{http://github.com/mdarby/mq}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{An email queue that actually works}
  s.test_files = [
    "test/helper.rb",
     "test/test_mq.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

